"""add document type column

Revision ID: 209814ea8e64
Revises: 236278f35c80
Create Date: 2026-09-25 13:28:27.934686

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "209814ea8e64"
down_revision: str | Sequence[str] | None = "236278f35c80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("document_type", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "document_type")
    # ### end Alembic commands ###
