"""add knowledge bases and link to documents

Revision ID: e3abe80eea9f
Revises: f6479a21dd18
Create Date: 2026-10-01 19:38:41.137109

"""
from typing import Sequence, Union

from datetime import datetime
from uuid import uuid4

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3abe80eea9f'
down_revision: str | Sequence[str] | None = 'f6479a21dd18'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create knowledge_bases table
    op.create_table(
        'knowledge_bases',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('knowledge_bases_pkey'))
    )
    op.create_index(op.f('ix_knowledge_bases_slug'), 'knowledge_bases', ['slug'], unique=True)

    # Insert default knowledge base
    default_kb_id = uuid4()
    op.execute(
        sa.text(
            f"INSERT INTO knowledge_bases (id, name, slug, created_at, updated_at) VALUES ('{default_kb_id}', 'Default Knowledge Base', 'default', '{datetime.utcnow().isoformat()}', '{datetime.utcnow().isoformat()}')"
        )
    )

    # Add documents.knowledge_base_id as nullable
    op.add_column('documents', sa.Column('knowledge_base_id', postgresql.UUID(as_uuid=True), nullable=True))

    # Assign existing documents to default KB
    op.execute(
        sa.text(
            f"UPDATE documents SET knowledge_base_id = '{default_kb_id}' WHERE knowledge_base_id IS NULL"
        )
    )

    # Make knowledge_base_id NOT NULL
    op.alter_column(
        'documents',
        'knowledge_base_id',
        existing_type=postgresql.UUID(),
        nullable=False,
        existing_nullable=True,
    )

    # Add foreign key
    op.create_foreign_key(
        op.f('fk_documents_knowledge_base_id_knowledge_bases'),
        'documents',
        'knowledge_bases',
        ['knowledge_base_id'],
        ['id'],
        ondelete='RESTRICT'
    )

    # Add index
    op.create_index(op.f('ix_documents_knowledge_base_id'), 'documents', ['knowledge_base_id'], unique=False)

    # ### end Alembic commands ###